force-app/main/default/objects/Train_Shedule__c/Train_Shedule__c.object-meta.xml
<CustomObject>
    <label>Train Shedule</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>TrainSheduleNum</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Train Shedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Train_Shedule__c/fields/Bedroll_Required__c.field-meta.xml
<CustomField>
    <fullName>Bedroll_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Bedroll Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Train_Shedule__c/fields/Boarding_Station__c.field-meta.xml
<CustomField>
    <fullName>Boarding_Station__c</fullName>
    <label>Boarding Station</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Train_Shedule__c/fields/Booking_Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Open_Date__c</fullName>
    <formula>IF( Is_Talkal__c == TRUE ,  Date_of_Journey__c - 1 ,  Date_of_Journey__c - 120)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Booking Open Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Train_Shedule__c/fields/Date_of_Journey__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Journey__c</fullName>
    <label>Date of Journey</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Train_Shedule__c/fields/Destination_Station__c.field-meta.xml
<CustomField>
    <fullName>Destination_Station__c</fullName>
    <label>Destination Station</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Train_Shedule__c/fields/Is_Ac__c.field-meta.xml
<CustomField>
    <fullName>Is_Ac__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Ac Ticket</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Train_Shedule__c/fields/Is_Talkal__c.field-meta.xml
<CustomField>
    <fullName>Is_Talkal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Talkal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Train_Shedule__c/fields/Name_of_Person__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name of Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Train Shedule</relationshipLabel>
    <relationshipName>Train_Shedule</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Train_Shedule__c/fields/Planned_Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Booking_Date__c</fullName>
    <label>Planned Booking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Train_Shedule__c/fields/Status_of_Booking__c.field-meta.xml
<CustomField>
    <fullName>Status_of_Booking__c</fullName>
    <label>Status of Booking</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Train_Shedule__c/fields/Train_Name_Code__c.field-meta.xml
<CustomField>
    <fullName>Train_Name_Code__c</fullName>
    <label>Train Name/Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TrainSheduleController.cls
public with sharing class TrainSheduleController {
    
    @AuraEnabled(cacheable = true)
    public static List<Train_Shedule__c> getAllJourneyInit()
    {
        List<Train_Shedule__c> listRecords= new List<Train_Shedule__c>();
        Date myDate= date.today();
        listRecords=[SELECT Id, Name, CreatedDate, Boarding_Station__c, Destination_Station__c, 
                     Planned_Booking_Date__c, Is_Talkal__c, Train_Name_Code__c, Name_of_Person__c, Age__c, Is_Ac__c,
                     Bedroll_Required__c, Status_of_Booking__c, Date_of_Journey__c, Booking_Open_Date__c FROM Train_Shedule__c 
                     where Date_of_Journey__c>= :myDate and Date_of_Journey__c<= :myDate+7 ];
        //system.debug(listRecords.size()+100);
        return listRecords;
    }
}